### ISSUE TITLE
Can this be installed using sbt?

### ISSUE THREAD

**Issue by jstncno** [ept/warc-hadoop#3]
Hi, fairly new to Java, Scala, Hadoop, and Spark. I've been following some Scala Spark tutorials, and I'm wondering if this can be installed using sbt.

Thanks in advance.

**Comment by ept** [comment]
I believe sbt can download Maven dependencies, so it ought to work. Try this:

```
libraryDependencies += "com.martinkl.warc" % "warc-hadoop" % "0.1.0"
```

**Comment by jstncno** [comment]
Wow, that easy. Thanks for the quick and helpful response!
